version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-row_level_security_db}
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/${POSTGRES_DB:-row_level_security_db}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      PORT: ${PORT:-8080}
      ENVIRONMENT: ${ENVIRONMENT:-development}
    volumes:
      - ./migrations:/root/migrations
    env_file:
      - .env

volumes:
  postgres_data: